### ISSUE TITLE
encountered  this bug when running the app

### ISSUE THREAD

**Issue by Phant0m-a** [Iamabdulquddus/karyana-wala#1]
Error: unable to find directory entry in pubspec.yaml: C:\Users\Ahsan Ali\Documents\karyana-wala\assets\images\
Error: unable to find directory entry in pubspec.yaml: C:\Users\Ahsan Ali\Documents\karyana-wala\assets\icons\

**Comment by Iamabdulquddus** [comment]
hn ya add na hoi pata na keya bana ... ya do files bana loo .... I guess ...

**Comment by Phant0m-a** [comment]
im updateing the android studio now.... slow internet sucks!😐

**Comment by Iamabdulquddus** [comment]
good

**Comment by Phant0m-a** [comment]
ok 👍
